name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Targets and Tools
        run: |
          rustup target add thumbv7em-none-eabi
          rustup target add thumbv7m-none-eabi
          rustup target add thumbv6m-none-eabi
          rustup component add llvm-tools-preview
    
      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binutils@0.3.6 

      - name: Unpack disk
        run: zcat src/disk.img.gz > src/disk.img

      - name: Check Syntax
        run: |
          cargo check

      - name: Build Release
        run: |
          cargo build --target=thumbv6m-none-eabi
          cargo build --target=thumbv7m-none-eabi
          cargo build --target=thumbv7em-none-eabi
          cargo build --release --target=thumbv6m-none-eabi
          cargo build --release --target=thumbv7m-none-eabi
          cargo build --release --target=thumbv7em-none-eabi

      - name: Size
        run: |
          cargo size --target=thumbv6m-none-eabi -- -A
          cargo size --target=thumbv7m-none-eabi -- -A
          cargo size --target=thumbv7em-none-eabi -- -A
          cargo size --release --target=thumbv6m-none-eabi -- -A
          cargo size --release --target=thumbv7m-none-eabi -- -A
          cargo size --release --target=thumbv7em-none-eabi -- -A

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{success()}}
        with:
          name: Artifacts
          if-no-files-found: error
          path: |
            ./target/thumbv6m-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv6m-none-eabi/release/neotron-qemu-bios
            ./target/thumbv7m-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv7m-none-eabi/release/neotron-qemu-bios
            ./target/thumbv7em-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv7em-none-eabi/release/neotron-qemu-bios

      - name: Upload files to Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/thumbv6m-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv6m-none-eabi/release/neotron-qemu-bios
            ./target/thumbv7m-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv7m-none-eabi/release/neotron-qemu-bios
            ./target/thumbv7em-none-eabi/debug/neotron-qemu-bios
            ./target/thumbv7em-none-eabi/release/neotron-qemu-bios
