name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Add Target
      run: rustup target add thumbv7m-none-eabi
    - name: Build
      run: cargo build --verbose --target=thumbv7m-none-eabi
